# Generated by Django 5.0.7 on 2025-02-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_is_doctor_doctorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_doctor',
        ),
    ]
